force-app/main/default/objects/OpportunityLineItem/fields/Diff_quantite_stock__c.field-meta.xml
<CustomField>
    <fullName>Diff_quantite_stock__c</fullName>
    <label>Diff quantite stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityProductsController.cls
public with sharing class OpportunityProductsController {
    @AuraEnabled(cacheable=true)
    //Methode statique pour récupérer les OpportunityLineItems associés à une opportunité//
    //Prend en paramètre une requete SOQL afin de recuperer les champs ci-dessous//
    public static List<OpportunityLineItem> getOpportunityLineItems(Id opportunityId) {
        return [
            SELECT Id, UnitPrice, TotalPrice, Quantity,
                   Product2.Name, Product2.QuantityInStock__c,Diff_quantite_stock__c
            FROM OpportunityLineItem
            WHERE OpportunityId = :opportunityId
        ];
    }
}